name: formio
description: A dynamic form rendering and submission package for Flutter using Form.io schemas.
version: 0.1.2
homepage: https://spinex.io
repository: https://github.com/mskayali/formio_flutter
issue_tracker: https://github.com/mskayali/formio_flutter/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  dio: ^5.9.0
  provider: ^6.1.5
  file_picker: ^8.1.2
  flutter_html: ^3.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
